"""Add UserOTP table

Revision ID: 297f5f3a6443
Revises: da39b33a35ad
Create Date: 2026-02-02 12:51:03.319430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '297f5f3a6443'
down_revision: Union[str, Sequence[str], None] = 'da39b33a35ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_otps_email'), 'user_otps', ['email'], unique=False)
    op.create_index(op.f('ix_user_otps_id'), 'user_otps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_otps_id'), table_name='user_otps')
    op.drop_index(op.f('ix_user_otps_email'), table_name='user_otps')
    op.drop_table('user_otps')
    # ### end Alembic commands ###
